version: "3"
services:
  postgres:
    image: postgres:12.3-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./:/var/lib/postgresql/data
    ports:
      - "5432:5432"
